dwa_planner_node:
  Subscribed_Topics:
    goal: "/localgoal_generator_node/goal"
    pointcloud: "/laser_fake"

  Published_Topics:
    velocity: "/cmd_vel"
    velocity_window: "window"

  Parameters:
    ## -- Frame Ids
    base_frameId: "base_link"
    map_frameId: "map"

    ## -- Duration
    velocity_publish_duration: 0.1 # 10Hz
    velocityWindow_publish_duration: 0.1

    ## -- Kinematic constraints
    has_max_wheel_velocity: false
    wheelbase_length: 0.6
    max_wheel_velocity: 0.7

    ## -- Velocity constraints (User settings)
    max_linear_velocity: 1.0 # desired robot speed
    max_angular_velocity: 0.8

    ## -- Collision check parameters
    collisionCheck_timeHorizon: 7.0 # timeHorizon x maxLinerVel = max collisionCheck distance
    robot_radius: 0.7 # physical robot size for collision check
    safety_margin: 9 # velocity space margin from obstacle area

    ## -- DWA parameter
    optimization_timeHorizon: 3.0 # timeHorizon x maxLinerVel = min localGoal distance
    target_heading: 1.0
    clearance: 1.0
    velocity: 1.0
